#!/bin/bash
# Xsetup - run as root before the login dialog appears
RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LOG_FILE=/var/log/eta.log
OPTICTOUCH_PID=/var/run/optictouch.pid

echo -e "${RED}$0" >> $LOG_FILE
u=$(/usr/bin/whoami)
echo -e "${RED}$0${NC} : running as ${YEL}$u" >> $LOG_FILE

sleep 3

while [ ! -f $OPTICTOUCH_PID ]
do
    sleep 1
done

if [ -f /boot/efi/EFI/microsoft/BOOT/bootmgfw.efi ] || grep -q "Windows" /boot/grub/grub.cfg ; then
    if [ ! -e /bin/live-boot ] && [ ! -e /bin/live-config ] ; then
       if  [ ! -f /var/run/etacoser.pid ] ; then
           touch /var/run/etacoser.pid
           etacoser
       else
           echo -e "${RED}$0 ${NC}: etacoser.pid found" >> /tmp/eta_log
       fi
    fi
fi

echo -e "${RED}$0${NC} : done." >> $LOG_FILE

#xconsole -geometry 480x130-0-0 -notify -verbose -fn fixed -exitOnFail -file /dev/xconsole &

