#! /bin/bash
# Xstartup - run as root before session starts
RED='\033[1;31m'
YEL='\033[1;33m'
NC='\033[0m' # No Color
PATH="$PATH:/usr/bin/X11"

if [ ! -f /tmp/eta_log ]; then
    touch /tmp/eta_log
    chmod 777 /tmp/eta_log
fi

echo -e "${RED}$0" >> /tmp/eta_log
u=`/usr/bin/whoami`
echo -e "${RED}$0 ${NC}running as ${YEL}$u" >> /tmp/eta_log
removed=`rm -rvf /tmp/.virtualkeyboard`
echo -e "${RED}$0 ${YEL}$removed"

echo -e "${RED}$0 ${NC}calling check_optictouch & " >> /tmp/eta_log
/usr/bin/check_optictouch &

if [ -e /etc/nologin ]; then
  # always display the nologin message, if possible
  if [ -s /etc/nologin ] && which xmessage > /dev/null 2>&1; then
    xmessage -file /etc/nologin -geometry 640x480
  fi
  if [ "$(id -u)" != "0" ] && \
     ! grep -qs '^ignore-nologin' /etc/kde4/kdm/kdm.options; then
    exit 1
  fi
fi

# NOTE: The session is aborted if the last command returns non-zero.
